kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
# TODO make part of a kustomization
  type: NodePort
  ports:
    - port: 80
      name: scdf-server
  selector:
    app: scdf-server
