apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    spring:
      cloud:
        dataflow:
          task:
            platform:
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 2048Mi
#                      
# TODO - enable replacement of database url.  
# Secret comes from deployment-patch                        
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: ${database-username}
        password: ${database-password}
        testOnBorrow: true
        validationQuery: "SELECT 1"

